global:
  cloud: others
  clusterName: home-ops
  deploymentEnvironment: production
otelCollectorEndpoint: signoz-otel-collector.observability.svc.cluster.local:4317
otelInsecure: true
presets:
  otlpExporter:
    enabled: true
  hostMetrics:
    enabled: true
    collectionInterval: 30s
  logsCollection:
    enabled: true
  kubeletMetrics:
    enabled: true
    insecureSkipVerify: false
  kubernetesAttributes:
    enabled: true
  clusterMetrics:
    enabled: true
  k8sEvents:
    enabled: true
