controllers:
  redbot:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/phasecorex/red-discordbot
          tag: full@sha256:9bd6e896e967ee117115925bcb644a5aa9f2030aa4df490027c395d64c07b908
        env:
          PREFIX: "?"
          TZ: Pacific/Auckland
        envFrom:
          - secretRef:
              name: redbot-secret
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 512Mi
persistence:
  config:
    existingClaim: redbot
    globalMounts:
      - path: /data