controllers:
  redbot:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/phasecorex/red-discordbot
          tag: full@sha256:314a3bb90f961b5805f06a75945ec9c133caa5e14c157ae84c743f4e37f7e174
        env:
          PREFIX: "?"
          TZ: Pacific/Auckland
        envFrom:
          - secretRef:
              name: redbot-secret
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 512Mi
persistence:
  config:
    existingClaim: redbot
    globalMounts:
      - path: /data