---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "darkflame-dev-production"
spec:
  secretName: "darkflame-dev-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "darkflame.dev"
  dnsNames: ["darkflame.dev", "*.darkflame.dev"]
