# ---
# crds:
#   enabled: true
#   # upgradeJob:
#   #   enabled: true
#   #   forceConflicts: true

# cleanPrometheusOperatorObjectNames: true

# alertmanager:
#   route:
#     main:
#       annotations:
#         gatus.home-operations.com/endpoint: |-
#           group: Observability
#       enabled: true
#       hostnames:
#         - "alertmanager.darkflame.dev"
#       parentRefs:
#         - name: envoy-internal
#           namespace: network

#   alertmanagerSpec:
#     alertmanagerConfiguration:
#       name: alertmanager
#       global:
#         resolveTimeout: 5m
#     externalUrl: https://alertmanager.darkflame.dev

# kubeEtcd:
#   service:
#     selector:
#       component: kube-apiserver # etcd runs on control plane nodes

# kubeProxy:
#   enabled: false

# prometheus:
#   route:
#     main:
#       annotations:
#         gatus.home-operations.com/endpoint: |-
#           group: Observability
#       enabled: true
#       hostnames:
#         - "prometheus.darkflame.dev"
#       parentRefs:
#         - name: envoy-internal
#           namespace: network

#   prometheusSpec:
#     securityContext:
#       runAsNonRoot: true
#       runAsUser: 64535
#       runAsGroup: 64535
#       fsGroup: 64535
#     podMonitorSelectorNilUsesHelmValues: false
#     probeSelectorNilUsesHelmValues: false
#     ruleSelectorNilUsesHelmValues: false
#     scrapeConfigSelectorNilUsesHelmValues: false
#     serviceMonitorSelectorNilUsesHelmValues: false
#     retention: 30d
#     retentionSize: 70GB
#     resources:
#       requests:
#         cpu: 100m
#         memory: 512Mi
#       limits:
#         memory: 4Gi
#     storageSpec:
#       volumeClaimTemplate:
#         spec:
#           storageClassName: openebs-hostpath
#           resources:
#             requests:
#               storage: 75Gi

# prometheus-node-exporter:
#   fullnameOverride: node-exporter
#   prometheus:
#     monitor:
#       enabled: true
#       relabelings:
#         - action: replace
#           regex: (.*)
#           replacement: $1
#           sourceLabels:
#             - "__meta_kubernetes_pod_node_name"
#           targetLabel: kubernetes_node

# kube-state-metrics:
#   fullnameOverride: kube-state-metrics
#   metricLabelsAllowlist:
#     - pods=[*]
#     - deployments=[*]
#     - persistentvolumeclaims=[*]
#   prometheus:
#     monitor:
#       enabled: true
#       relabelings:
#         - action: replace
#           regex: (.*)
#           replacement: $1
#           sourceLabels:
#             - "__meta_kubernetes_pod_node_name"
#           targetLabel: kubernetes_node

# grafana:
#   enabled: false
#   forceDeployDashboards: true
