---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./argocd-cmd-params-cm.yaml
  - ./applications.yaml
  - ./repositories.yaml
  - ./settings.yaml
  # - ./http-route.yaml
  - ./notifications-cm.yaml
  - ./notifications-secret.yaml