fullnameOverride: &app minecraft
deploymentAnnotations:
  reloader.stakater.com/auto: "true"
image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.1.2-java21@sha256:223c1135c98683d0af80b4c20b5b566bea5ecc717d01780b610fd8a6839f7e5d
  pullPolicy: IfNotPresent
livenessProbe:
  initialDelaySeconds: 120
serviceAnnotations:
  external-dns.alpha.kubernetes.io/hostname: mc.darkflame.dev
  external-dns.alpha.kubernetes.io/target: mc-router.darkflame.dev
  mc-router.itzg.me/externalServerName: mc.darkflame.dev
minecraftServer:
  difficulty: "normal"
  eula: "true"
  memory: 8G
  motd: "Testing"
  ops: "Darkflame72"
  overrideServerProperties: true
  spawnProtection: 0
  type: "PAPER"
  version: "1.21.11"
  viewDistance: 8
persistence:
  dataDir:
    enabled: true
    existingClaim: *app
extraEnv:
  ENABLE_ROLLING_LOGS: "true"
  ENFORCE_WHITELIST: "true"
  RCON_CMDS_STARTUP: |-
    gamerule doFireTick false
    gamerule playersSleepingPercentage 0
  SIMULATION_DISTANCE: "4"
  SNOOPER_ENABLED: "false"
  SYNC_CHUNK_WRITES: "false"
resources:
  requests:
    cpu: 1
    memory: 8Gi
  limits:
    memory: 10Gi
