---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-configmap
data:
  config.yaml: |
    ---
    originRequest:
      originServerName: "external.darkflame.dev"

    ingress:
      - hostname: "darkflame.dev"
        service: &svc https://envoy-external.kube-system.svc.cluster.local
      - hostname: "*.darkflame.dev"
        service: *svc
      - service: http_status:404