---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./check-deprecated-apis.yaml
  - ./disallow-latest-tag.yaml
  - ./require-drop-all.yaml
  - ./require-pod-requests-limits.yaml
  - ./require-readonly-root-filesystem.yaml
