---
fullnameOverride: k8s-gateway
domain: "darkflame.dev"
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: "10.0.60.11"
  externalTrafficPolicy: Cluster
watchedResources: ["HTTPRoute", "Service"]